version: 2

defaults: &defaults
  working_directory: /go/src/github.com/sylabs/cri
  docker:
    - image: golang:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install dependencies
          command: apt-get update && apt-get install -y build-essential libssl-dev uuid-dev squashfs-tools
      - run:
          name: Build Source
          command: make build
      - run:
          name: Check Formatting
          command: test -z $(go fmt ./...)
      - run:
          name: Vet Source
          command: go vet -all ./...
      - run:
          name: Run Tests
          command: make test

  get_source:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Set Up Vendor Directory
          command: |
            if [ ! -d vendor ]; then
              curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure -vendor-only
            fi
      - run:
          name: singularity 3.0 build config
          command: |
            apt-get update && apt-get install -y build-essential libssl-dev uuid-dev squashfs-tools
      - save_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

  build_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Source
          command: make build

  check_formatting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Check Formatting
          command: test -z $(go fmt ./...)

  vet_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Vet Source
          command: go vet -all ./...

  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Run Tests
          working_directory: /go/src/github.com/sylabs/cri
          command: make test

workflows:
  version: 2

  build_and_test:
    jobs:
      - get_source
      - build_source:
          requires:
            - get_source
      - check_formatting:
          requires:
            - get_source
      - vet_source:
          requires:
            - get_source
      - unit_test:
          requires:
            - get_source